In [ ]:
!

In [1]:
import pandas as pd
import numpy as np

In [35]:
a = np.array([[1,2], [3, 4]])
b = np.array([[56,3], [48, 3]])

In [38]:
a_min = a.min(axis=1)
a_max = a.max(axis=1)

In [41]:
a

array([[1, 2],
       [3, 4]])

In [42]:
a_min

array([1, 3])

In [43]:
(a - a_min) / a_max

array([[ 0.  , -0.25],
       [ 1.  ,  0.25]])

In [19]:
def get_euclidean_distance(x1: np.ndarray, x2: np.ndarray) -> float:
    return ((x1 - x2) ** 2).sum() ** 0.5

In [6]:
def get_manhattan_distance(x1: np.ndarray, x2: np.ndarray) -> float:
    return (x1 - x2).sum()

In [17]:
def get_hamming_distance(x1: np.ndarray, x2: np.ndarray) -> int:
    return (x1 != x2).sum()

In [ ]:
def get_matching_distance(x1: np.ndarray, x2: np.ndarray) -> int:
    return (x1 != x2).mean()

In [26]:
def min_max_normalize(x: np.ndarray) -> np.ndarray:
    max_element = x.max()
    min_element = x.mean()